import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Global/Footer";
import Header from "@/components/Global/Header";
import SocialLink from "@/components/Global/SocialLink";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="relative z-10 bg-white">
          <div className="min-h-[55vh] py-global bg-white">
              {children}
          </div>
        <SocialLink />
        </main>
        <Footer />
      </body>
    </html>
  );
}
